AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 125

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
